class DevelopmentConfig(object):
  DEBUG = True
  SECRET_KEY='secret_key'
  AWS_ACCESS_KEY='AWS_ACCESS_KEY'
  AWS_SECRET_ACCESS_KEY='AWS_SECRET_ACCESS_KEY'
  DYNAMODB_ENDPOINT_URL='http://localhost:8000'
  DYNAMODB_REGION=''
  MAX_THREAD_SIZE=20